# -*- coding: utf-8 -*-
"""Ravdess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxQrUngjWKFXoR0PARvTHR51rsstU9fe
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import VGG16, InceptionV3
import librosa
import librosa.display
import cv2

tf.random.set_seed(42)
np.random.seed(42)

dataset_path = "/kaggle/input/ravdess-emotional-speech-audio/"
dataset_path

def parse_ravdess_filename(filename):

    parts = filename.split('-')
    emotion_code = int(parts[2])

    emotion_map = {
        1: 'neutral', 2: 'calm', 3: 'happy', 4: 'sad',
        5: 'angry', 6: 'fearful', 7: 'disgust', 8: 'surprised'
    }

    return emotion_map.get(emotion_code, 'unknown')

def load_ravdess_data(dataset_path):

    audio_files = []
    labels = []

    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            if file.endswith('.wav'):
                file_path = os.path.join(root, file)
                emotion = parse_ravdess_filename(file)

                if emotion != 'unknown':
                    audio_files.append(file_path)
                    labels.append(emotion)

    return audio_files, labels

def audio_to_mel_spectrogram(audio_path, target_size=(224, 224)):

    try:
        y, sr = librosa.load(audio_path, sr=None)

        mel_spect = librosa.feature.melspectrogram(
            y=y, sr=sr, n_mels=128, fmax=8000
        )

        log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
        log_mel_spect_resized = cv2.resize(log_mel_spect, target_size)

        log_mel_spect_normalized = (log_mel_spect_resized - log_mel_spect_resized.min()) / (
            log_mel_spect_resized.max() - log_mel_spect_resized.min() + 1e-8
        )

        return log_mel_spect_normalized

    except Exception as e:
        print(f"Error processing {audio_path}: {str(e)}")
        return None

def prepare_dataset(audio_files, labels, target_size=(224, 224)):

    X = []
    y_processed = []

    emotion_to_idx = {
        'neutral': 0, 'calm': 1, 'happy': 2, 'sad': 3,
        'angry': 4, 'fearful': 5, 'disgust': 6, 'surprised': 7
    }

    print("Converting audio files to Mel spectrograms...")
    for i, (audio_path, emotion) in enumerate(zip(audio_files, labels)):
        if i % 100 == 0:
            print(f"Processed {i}/{len(audio_files)} files")

        mel_spect = audio_to_mel_spectrogram(audio_path, target_size)
        if mel_spect is not None:
            mel_spect = np.expand_dims(mel_spect, axis=-1)
            X.append(mel_spect)
            y_processed.append(emotion_to_idx[emotion])

    return np.array(X), np.array(y_processed)

def create_cnn_x_model(input_shape=(224, 224, 1), num_classes=8):
    """论文提出的CNN-X模型"""
    model = keras.Sequential([
        # 第一个卷积块
        layers.Conv2D(8, (3, 3), activation='relu', padding='same',
                      input_shape=input_shape, name='conv1'),
        layers.AveragePooling2D((2, 2), name='pool1'),

        # 第二个卷积块
        layers.Conv2D(16, (3, 3), activation='relu', padding='same', name='conv2'),
        layers.AveragePooling2D((2, 2), name='pool2'),

        # 第三个卷积块
        layers.Conv2D(32, (3, 3), activation='relu', padding='same', name='conv3'),
        layers.AveragePooling2D((2, 2), name='pool3'),

        # 展平层
        layers.Flatten(),

        # 全连接层
        layers.Dense(2048, activation='relu', name='fc1'),
        layers.Dense(2048, activation='relu', name='fc2'),
        layers.Dense(num_classes, activation='softmax', name='output')
    ])

    return model

def create_vgg16_model(input_shape=(224, 224, 3), num_classes=8):
    """VGG-16模型 - 修复版本（使用3通道输入）"""
    # 直接使用3通道输入
    inputs = keras.Input(shape=input_shape)

    #3VGG16
    base_model = VGG16(weights='imagenet', include_top=False, input_tensor=inputs)
    base_model.trainable = False
    x = layers.GlobalAveragePooling2D()(base_model.output)
    x = layers.Dense(512, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = keras.Model(inputs, outputs)
    return model

def create_inceptionv3_model(input_shape=(224, 224, 3), num_classes=8):
    """InceptionV3"""
    inputs = keras.Input(shape=input_shape)
    InceptionV3
    base_model = InceptionV3(weights='imagenet', include_top=False, input_tensor=inputs)
    base_model.trainable = False


    x = layers.GlobalAveragePooling2D()(base_model.output)
    x = layers.Dense(512, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = keras.Model(inputs, outputs)
    return model

def convert_to_3channels(X):

    return np.repeat(X, 3, axis=-1)

def create_mlp_model(input_shape=(224, 224, 1), num_classes=8):

    model = keras.Sequential([
        layers.Flatten(input_shape=input_shape),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

print("Loading RAVDESS dataset...")
audio_files, labels = load_ravdess_data(dataset_path)

print(f"Total audio files: {len(audio_files)}")
print("Emotion distribution:")
print(pd.Series(labels).value_counts())

if not audio_files:
    print("\nError: No audio files were found in the dataset path.")
    print(f"Please check if the path '{dataset_path}' is correct and contains '.wav' files.")
    print("If you are running in a Kaggle environment, ensure the dataset is added correctly.")
    # Exit or raise an error to prevent further execution with empty data
    # For a notebook, a print statement is usually enough to signal the issue.
else:
    # 准备单通道数据（用于CNN-X和MLP）
    print("Preparing single-channel dataset...")
    X, y = prepare_dataset(audio_files, labels)

    # 准备3通道数据（用于VGG16和InceptionV3）
    print("Converting to 3 channels for VGG16 and InceptionV3...")
    X_3ch = convert_to_3channels(X)

    # 划分单通道数据集
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.66, random_state=42, stratify=y_temp
    )

    # 划分3通道数据集（保持相同的索引）
    X_train_3ch, X_temp_3ch, y_train_3ch, y_temp_3ch = train_test_split(
        X_3ch, y, test_size=0.3, random_state=42, stratify=y
    )
    X_val_3ch, X_test_3ch, y_val_3ch, y_test_3ch = train_test_split(
        X_temp_3ch, y_temp_3ch, test_size=0.66, random_state=42, stratify=y_temp_3ch
    )

    print(f"Single-channel - Training: {X_train.shape}, Test: {X_test.shape}")
    print(f"3-channel - Training: {X_train_3ch.shape}, Test: {X_test_3ch.shape}")

def train_and_evaluate_model(model, model_name, X_train, y_train, X_val, y_val, X_test, y_test, epochs=20):
    """训练和评估单个模型"""
    print(f"\n{'='*50}")
    print(f"Training {model_name}")
    print(f"{'='*50}")

    # 编译模型
    model.compile(
        optimizer=keras.optimizers.RMSprop(
            learning_rate=0.001,  # 学习率
            momentum=0.8,         # 动量 - 论文中提到的参数
            rho=0.9               # RMSprop的rho参数
        ),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # 回调函数
    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor='val_accuracy',
            patience=5,
            restore_best_weights=True
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=3,
            min_lr=1e-7
        )
    ]

    # 训练模型
    history = model.fit(
        X_train, y_train,
        batch_size=32,
        epochs=epochs,
        validation_data=(X_val, y_val),
        callbacks=callbacks,
        verbose=1
    )

    # 评估模型
    test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)

    # 预测
    y_pred = model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)

    # 计算其他指标
    from sklearn.metrics import precision_score, recall_score, f1_score
    precision = precision_score(y_test, y_pred_classes, average='weighted')
    recall = recall_score(y_test, y_pred_classes, average='weighted')
    f1 = f1_score(y_test, y_pred_classes, average='weighted')

    print(f"\n{model_name} Results:")
    print(f"Test Accuracy: {test_accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")

    return {
        'model_name': model_name,
        'model': model,
        'history': history,
        'test_accuracy': test_accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'y_pred': y_pred_classes
    }

'CNN-X (Proposed)': create_cnn_x_model(input_shape=(224, 224, 1)),
    'MLP': create_mlp_model(input_shape=(224, 224, 1))
}

models_3ch = {
    'VGG-16': create_vgg16_model(input_shape=(224, 224, 3)),
    'InceptionV3': create_inceptionv3_model(input_shape=(224, 224, 3))
}

# 存储所有结果
results = {}

print("Training single-channel models...")
# 训练单通道模型
for name, model in models_single_ch.items():
    try:
        result = train_and_evaluate_model(
            model, name, X_train, y_train, X_val, y_val, X_test, y_test, epochs=20
        )
        results[name] = result
    except Exception as e:
        print(f"Error training {name}: {str(e)}")
        continue

print("\nTraining 3-channel models...")
# 训练3通道模型
for name, model in models_3ch.items():
    try:
        result = train_and_evaluate_model(
            model, name, X_train_3ch, y_train, X_val_3ch, y_val, X_test_3ch, y_test, epochs=20
        )
        results[name] = result
    except Exception as e:
        print(f"Error training {name}: {str(e)}")
        continue

print(f"\nSuccessfully trained {len(results)} out of 4 models")